### ISSUE TITLE
Work together?

### ISSUE THREAD

**Issue by tak1n** [johannhof/lava#1]
Hey there, I'm currently working on a static site generator for rust so I would like to work together with you. :)

My current status: https://github.com/bennyklotz/cobalt.rs

**Comment by johannhof** [comment]
By all means, yes. Left alone I produce terrible code.

**Comment by johannhof** [comment]
I'll shoot you an email, you speak German, right?

**Comment by tak1n** [comment]
Me too, rust is a real complex programming language in my opinion :)
Yep I speak german.

My email: r3qnbenni@gmail.com
My Skype account: linkin.park.rockz

Just leave me an email or add me at skype :)

**Comment by tak1n** [comment]
@johannhof I made an github org and forked my repo there.
Also I invited you to the org.

https://github.com/cobalt-org/cobalt.rs
