### ISSUE TITLE
"cargo build --release" encounter error

### ISSUE THREAD

**Issue by luckypoem** [johannhof/lava#3]
hi.

root@AR:/usr/local/lava-site# cargo build --release
    Updating git repository `https://github.com/johannhof/markdown.rs.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading pipeline v0.5.0
   Compiling pipeline v0.5.0
   Compiling regex-syntax v0.3.9
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling libc v0.2.17
   Compiling utf8-ranges v0.1.3
   Compiling memchr v0.1.11
   Compiling aho-corasick v0.5.3
   Compiling winapi v0.2.8
   Compiling thread-id v2.0.0
   Compiling thread_local v0.2.7
   Compiling regex v0.1.80
   Compiling markdown v0.1.2 (https://github.com/johannhof/markdown.rs.git#cf473342)
   Compiling lava v0.1.0 (file:///usr/local/lava-site)
error: expected type, found `|`
   --> src/main.rs:165:54
    |
165 | fn copy_recursive(source: &Path, dest: &Path, valid: |&Path| -> bool) -> io::IoResult<()> {
    |                                                      ^

error[E0463]: can't find crate for `regex_macros`
 --> src/main.rs:3:1
  |
3 | extern crate regex_macros;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

error: Could not compile `lava`.

To learn more, run the command again with --verbose.
root@AR:/usr/local/lava-site#

how to fix it?
tks

**Comment by johannhof** [comment]
Hi there, this repo is outdated and unmaintained, it's the predecessor of [Cobalt](https://github.com/cobalt-org/cobalt.rs), which may be more what you're looking for.
